version: '3'

services:

  eureka-serviceregistry:
    build: ./eureka
    ports:
     - "8761:8761"
    tty: true
   
  zuul-service:
    build: ./zuul
    restart: always
    image: zuul-image
    volumes:
    - $USERPROFILE/.m2:/root/.m2
    ports:
    - "8081:8081"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
      

  vehicle-service:
    build: ./vehicle
    restart: always
    image: vehicle-image 
    volumes:
    - $USERPROFILE/.m2:/root/.m2
    ports:
    - "8082:8082"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
      
      
  user-service:
    build: ./user
    restart: always
    image: user-image 
    volumes:
    - $USERPROFILE/.m2:/root/.m2
    ports:
    - "8083:8083"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
      
      
  pricelist-service:
    build: ./pricelist
    restart: always
    image: pricelist-image 
    volumes:
    - $USERPROFILE/.m2:/root/.m2
    ports:
    - "8084:8084"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
      

  location-service:
    build: ./location
    restart: always
    image: location-image 
    volumes:
    - $USERPROFILE/.m2:/root/.m2
    ports:
    - "8085:8085"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
      
      
  catalogue-service:
    build: ./catalogue
    restart: always
    image: catalogue-image 
    volumes:
    - $USERPROFILE/.m2:/root/.m2
    ports:
    - "8086:8086"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
      
  request-service:
    build: ./request
    restart: always
    image: request-image 
    volumes:
    - $USERPROFILE/.m2:/root/.m2
    ports:
    - "8087:8087"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry


   

